site_name: VcA IT Documentation
repo_url: https://github.com/Viva-con-Agua/Viva-con-Agua.github.io
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/vca_logo_negativ.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
plugins:
  - search
  - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viva-con-agua
      name: Viva con Agua on GitHub
extra_css:
  - assets/extra.css