site_name: VcA IT Documentation
repo_url: https://github.com/Viva-con-Agua/Viva-con-Agua.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/vca_logo_negativ.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
plugins:
  - search
  - git-revision-date
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viva-con-agua
      name: Viva con Agua on GitHub
    - icon: material/web
      link: https://vivaconagua.org
      name: Viva con Agua Homepage
extra_css:
  - assets/extra.css

nav:
  - Home: "index.md"
  - Tutorials:
      - "tutorials/index.md"
  - How-To Guides:
      - "how-to-guides/index.md"
      - Writing Documentation: "how-to-guides/writing_documentation.md"
  - References:
      - "references/index.md"
      - Software Architecture: "references/software_architecture.md"
      - Secret Management: "references/secret_management.md"
      - DevOps:
          - "references/devops/index.md"
          - Continuous Delivery: "references/devops/cd.md"
          - Server Overview: "references/devops/server_overview.md"
          - Server Config & Orchestration: "references/devops/server_config.md"
          - Domain Deploy: "references/devops/domain_deploy.md"
      - Packages:
          - "references/packages/index.md"
          - vcago:
              - "references/packages/vcago/index.md"
              - Base Server: "references/packages/vcago/base_server.md"
  - Explanations:
      - "explanations/index.md"
