name: gh-pages-ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install pipenv
      - run: pipenv install --system --skip-lock
      - run: mkdocs gh-deploy --force --strict
